{% set version = "2025.4.1" %}

package:
  name: jsonschema-specifications
  version: {{ version }}

source:
  folder: src
  url: https://pypi.org/packages/source/j/jsonschema-specifications/jsonschema_specifications-{{ version }}.tar.gz
  sha256: 630159c9f4dbea161a6a2205c3011cc4f18ff381b189fff48bb39b9bf26ae608

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} {{ RECIPE_DIR }}/builder.py

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
    - python-build
  run:
    - python >={{ python_min }}
    - referencing >=0.31.0

test:
  imports:
    - jsonschema_specifications
  commands:
    - pip check
    - coverage run --source jsonschema_specifications --branch -m pytest -vv --color=yes --tb=long --pyargs jsonschema_specifications
    - coverage report --show-missing --skip-covered --fail-under=96
  requires:
    - pip
    - pytest
    - coverage
    - python {{ python_min }}

about:
  summary: The JSON Schema meta-schemas and vocabularies, exposed as a Registry
  home: https://github.com/python-jsonschema/jsonschema-specifications
  license: MIT
  license_file: src/COPYING
  doc_url: https://jsonschema-specifications.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
